# Site settings
name: Operation
email: 445701902@qq.com
author: Zheng Xianlin
url: 
resume_site: 
github: https://github.com/AaYyLink/
baseurl: "/Zheng-Xianlin-s-Blog"
description: Actually, less is more!
meta_description: 
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: AaYyLink

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

