# Site settings
name: Operation and Maintenance
email: 445701902@qq.com
author: Zheng Xianlin
url: 
resume_site: 
github: https://github.com/AaYyLink/
baseurl: "www.aayylink.com"
description: 逝者已矣，来者可追
meta_description: 郑贤琳;心有所向;将有所成
motto: 有智而性缓者思大智，有才而气和者为大才。
banner: 人所缺乏的不是才干而是志向，不是成功的能力而是勤劳的意志。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: AaYyLink

# Build settings
markdown: kramdown

baidu_analysis: e03425319145fcc83737bb5cbb661696

